rvm:
  - 1.9.2
  - 1.9.3
  
script: 
  - "cucumber"
  - "rspec"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mysql -e 'create database to_do_test;'"
  - "rake db:test:load --trace"

