development:
  adapter: mysql
  database: to-do-dev
  pool: 5
  timeout: 5000
  host: 127.0.0.1

test:
  adapter: mysql
  database: to-do-test
  pool: 5
  timeout: 5000
  host: 127.0.0.1

production:
  adapter: mysql
  database: to-do
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  
