development:
  adapter: mysql
  database: to-do-dev
  pool: 5
  timeout: 5000
  host: 127.0.0.1

test: &test
  adapter: mysql
  database: to_do_test
  username: root
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: to-do
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  

cucumber:
  <<: *test